### ISSUE TITLE
hackney connection pooling ?

### ISSUE THREAD

**Issue by msonawane** [boonious/hui#2]
What should be a better approach for hackney connection pool ?
a quick hack will be merging hackney :default pull in _search/4 as below.  Any pointers on doing it idiomatically?

  defp _search(url, headers, options, _bang) do
    options = Keyword.merge(options, hackney: [pool: :default])

    {status, resp} = get(url, headers, options)

    case status do
      :ok -> {:ok, resp}
      :error -> {:error, %Hui.Error{reason: resp.reason}}
    end
  end

**Comment by boonious** [comment]
Hey (what's your name?), yes that would be a quick hack and hardwire indeed. `_search/4` isn't intended to be used directly. 

According to https://github.com/edgurgel/httpoison#connection-pools, hackney connection pool can be specified as `HTTPoison` options. In `Hui`, all URL related parameters are encapsulated in the [`Hui.URL` struct](https://hexdocs.pm/hui/Hui.URL.html) with which you could use to specify HTTP matters e.g. headers and options. The struct is applicable to almost all `Hui` functions. You could simply pass the URL struct to functions such as [`Hui.search/2`](https://hexdocs.pm/hui/Hui.html#search/2),[`Hui.search/7`](https://hexdocs.pm/hui/Hui.html#search/7), or the underpinning [`Hui.Request.search/3`](https://hexdocs.pm/hui/Hui.Request.html#search/3).

For example - see `options` and `url` below,

```
    headers =  [{"accept", "application/json"}]
    options: [ recv_timeout: 10000, hackney: [pool: :default] ] # HTTPoison options
    solr_url = "http://solr_endpoint"
    
    url = %Hui.URL{url: solr_url, headers: headers , options: options}
 
    x = %Hui.Q{q: "solr rocks", rows: 10, start: 10, fq: ["type:article"]}
    y = %Hui.F{field: ["cat", "author_str"], mincount: 1}
    Hui.search(url, [x, y])
```

That **should** work. Please let me know.

If using struct is too tedious for you, `Hui` provides the underpinning HTTPoison functions. You can just do a `get/3` and pass headers and options information as keywords list:

```
    headers =  [{"accept", "application/json"}]
    options =  hackney: [pool: :default]

    Hui.Request.get("http...", headers, options)
```

Hope this helps.
